"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ROUTERSTATUS = void 0;
var ROUTERSTATUS;
(function (ROUTERSTATUS) {
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_ERROR"] = 1] = "ROUTER_ERROR";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_WARRING"] = 2] = "ROUTER_WARRING";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_SUCCESS"] = 3] = "ROUTER_SUCCESS";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_TIMEOUT"] = 10000] = "ROUTER_TIMEOUT";
    ROUTERSTATUS["ROUTER_HOST"] = "127.0.0.1";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_PORT"] = 8111] = "ROUTER_PORT";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_504"] = 504] = "ROUTER_504";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_200"] = 200] = "ROUTER_200";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_300"] = 300] = "ROUTER_300";
    ROUTERSTATUS[ROUTERSTATUS["ROUTER_INTER"] = 1000] = "ROUTER_INTER";
    ROUTERSTATUS["ROUTER_ABORTERROR"] = "AbortError";
})(ROUTERSTATUS || (exports.ROUTERSTATUS = ROUTERSTATUS = {}));
